### ISSUE TITLE
File doesn't seem to have have at least 2 lines of text

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#16]
Open following csv.

You get following error message 'File doesn't seem to have have at least 2 lines of text'

Opening it in Google Facet runs just fine.

[vektis_v40.csv.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4740740/vektis_v40.csv.zip)

**Comment by hansvana** [comment]
This file ends its lines with CR, not CRLF or LF. Which is an edge case I've honestly never seen before. Apparently it was used by old versions of MacOS.

Fixed in Alpha 0.2.3

**Comment by erikk-avans** [comment]
Looks okay now. I slimmed down the dataset.  But I do not see much patterns.
