### ISSUE TITLE
Training the model does not work

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#18]
classification (7 classes)

ignore animal_name
all but 'class_type' as input
class_type as output

Issue : 
[zoo2.csv.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4742956/zoo2.csv.zip)
Current loss shows as 'NaN' and model does not get trained.

**Comment by hansvana** [comment]
Caused by this ml5.js bug https://github.com/ml5js/ml5-website/issues/154 on features where all values 0 (e.g. `feathers`). It's not very hard to write a check for 'all 0 features', but it would add a lot of extra processing on large datasets.

**Comment by hansvana** [comment]
In Alpha 0.2.5 features where all the values are the same will display a warning and will be automatically set to ignore

**Comment by erikk-avans** [comment]
Checked. Works with the warning now. Well done!
