### ISSUE TITLE
credit

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#21]
getting error in training: in inputArray of normalizeArray() function.

See if you can make this one to work.

Classification on 'Class'. All features selected.

[credit-g.csv.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4864623/credit-g.csv.zip)

**Comment by hansvana** [comment]
This error was due to the code getting confused about if a feature was a number or a string. fixed by writing an extra check (detectColumnsDatatype) in alpha 0.2.3
