### ISSUE TITLE
marrital affair

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#22]
after being trained, the nbaffairs shows in a wrong format. Like 0.04 i.s.o 4.

This is a regression case.
[Extra_Marrital_affair.csv.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4864960/Extra_Marrital_affair.csv.zip)

**Comment by hansvana** [comment]
Not a bug, regression will always give a floating point number. If the user expects a rounded number, it can be rounded after the prediction is made.

On another matter: What columns are you using to train? I see very little / no correlation.

**Comment by erikk-avans** [comment]
dataset works okay now. There are some patterns : hi-prob for male, ym>10; age>30.
