### ISSUE TITLE
Divorce - attribuite set to zero not suported in testing model

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#29]
Load divorce.csv
Classification on all features - target is class
train the model and go to testing
enter 0 in one of the attribute --> it does not set the attribute to 0. Instead it is randmized to any value.

Other issue/feature request : it would be nice that the randmization during the testing does not use float but only integers. If the randomization detects float then float okay. If randomization detects only integers then no floatand only integers.

**Comment by hansvana** [comment]
Fixed and feature added in Alpha 0.2.8

**Comment by erikk-avans** [comment]
I tested it. Basically it works. The only odd thing is that it shows prediction = 1 where I expect prediction = 0 and vice versa.
