### ISSUE TITLE
Video Game Sales - All Prediction set to  0.01

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#31]
video game sales csv in the pool.
Select only the sales features (NA, EU, Japan, rest)
Target is global sales

Regression model
loss extremnly small (0.002)

issue : all predictions show 0.01

**Comment by hansvana** [comment]
This data has extreme outliers, which makes finding correlation impossible. Recommend filtering in Excel before training.

**Comment by erikk-avans** [comment]
You might want to redownload the dataset, I made some changes. There is some nice positive correlation between regions sales (europe, japan, NA) and global sales.  Global Sales has an average of 1.61 and a median of 1.04 so I do not expect all predictions to be set to 0.1

**Comment by erikk-avans** [comment]
Got rid of the outliers but predictions were still bad accuracy - Removed this dataset from the bunch. Case closed.
