### ISSUE TITLE
Doctor

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#4]
Doctor is the output
children, access, health are inputs
Model converges after 2 eopchs.
Issue : trained model always predicts 0 doctor visit
Unzip file
[Doctor.csv.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4678735/Doctor.csv.zip)
 (Github does not like csv)

**Comment by hansvana** [comment]
I'm seeing very little correlation in this dataset. No idea if that is related though. Does it train well in other training engines?

**Comment by erikk-avans** [comment]
A dataframe containing :

doctor
the number of doctor visits

children
the number of children in the household

access
is a measure of access to health care

health
a measure of health status (larger positive numbers are associated with poorer health)

**Comment by erikk-avans** [comment]
actually better to close. I like the concept but datas are not conclusive.

**Comment by hansvana** [comment]
I'll keep it open because I'd like to know why the loss reports as 0.1 when it's clearly much higher

**Comment by hansvana** [comment]
Closing because initial problem seems fixed in current version
