### ISSUE TITLE
Heart rate Disease

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#5]
Good dataset for classification. I simplified a bit and kept only the most impactful features.
More info on dataset : https://www.kaggle.com/tentotheminus9/what-causes-heart-disease-explaining-the-model
on cmd.camp, use all features as input; target is 'target'.
Training error los around 0,34

Issue : when I input manually data to test the model, it does not return any prediction.
[Heart_disease_v10.csv.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4704256/Heart_disease_v10.csv.zip)

**Comment by hansvana** [comment]
This should be fixed now

**Comment by erikk-avans** [comment]
I threw this dataset in Keras/Python with 2 hidden layers (16+4 neurons). Got 86% accuracy using 4 input parameters (the most important ones - documented on Kaggle). I kind a like this one.
