### ISSUE TITLE
Student_Exam_Performance

### ISSUE THREAD

**Issue by erikk-avans** [hansvana/ML5_NN_Trainer#6]
Everthing is fine until the model testing. It does not show any prediction. With or without entering data into the features.
[Students_Exam_Performance.csv.zip](https://github.com/hansvana/ML5_NN_Trainer/files/4706703/Students_Exam_Performance.csv.zip)

**Comment by hansvana** [comment]
what are you using as input and output? classification or regression?

**Comment by erikk-avans** [comment]
regression on math score. There is correlation between writing/reading/math score. Seems interesting. Using all inputs.

**Comment by hansvana** [comment]
I cannot reproduce the problem at this time. Which might be because it was fixed automagically with some update. @erikk-avans can you confirm this is now working as intended?

**Comment by erikk-avans** [comment]
it is fixed now. Checked.
